In [1]:
import numpy as np

# Create an array from an iterable

such as 

- list
- tuple
- range

Notice that not all iterables can be used to create a numpy array, such as `set` and `dict`.

In [4]:
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [6]:
arr1 = np.array((1,2,3,4,5))
arr1

array([1, 2, 3, 4, 5])

In [10]:
arr2= np.array(range(10))
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Creating an array with specified Data Type

In [13]:
arr = np.array([[1,2,3], [4,5,6]], dtype='i2')
print(arr)
print('Data Type: ' + str(arr.dtype))

[[1 2 3]
 [4 5 6]]
Data Type: int16


## Creating an array within specified range
`np.arange()` can be used to replace `np.array(range())` method 


In [16]:
arr = np.arange(0,21,2)
print(arr)

[ 0  2  4  6  8 10 12 14 16 18 20]


# Create an array of evenly spaced numbers within specified range

np.linspace(start, stop, num_of_elements, endpoint=True, retstep=False) has 5 parameters:

- start: start number (inclusive)
- stop: end number (inclusive unless endpoint set to False)
- num_of_elements: number of elements contained in the array
- endpoint: boolean value representing whether the stop number is inclusive or not
- retstep: boolean value representing whether to return the step size

In [19]:
arr, step_size = np.linspace(0,5,8, endpoint=False, retstep=True)
print(arr)
print('The step size is ' + str(step_size))


[0.    0.625 1.25  1.875 2.5   3.125 3.75  4.375]
The step size is 0.625


# Create an array of random values of given shape

- `
np.random.rand(`) method returns values in the range` [0,1`)

In [30]:
arr = np.random.rand(3,3)
print(arr)

[[0.43650164 0.56038295 0.1497008 ]
 [0.02477006 0.27571201 0.81952822]
 [0.94818164 0.51222022 0.72107288]]


# Create an array of zeros of given shape
- `
np.zeros` (): create array of all zeros in given sha
- `e
np.zeros_lik` e(): create array of all zeros with the same shape and data type as the given input array

In [45]:
zeros = np.zeros((2,3))
print(zeros)

[[0. 0. 0.]
 [0. 0. 0.]]


In [51]:
arr = np.array([[1,2], [3,4],[5,6]], dtype=np.float_)
zeros = np.zeros_like(arr)
print(zeros)
print('Data Type: ' + str(zeros.dtype))

[[0. 0.]
 [0. 0.]
 [0. 0.]]
Data Type: float64


# Create an array of ones of given shape
- `np.ones()`): create array of all ones in given shap
- `
np.ones_like`(): create array of all ones with the same shape and data type as the given input array

In [61]:
ones = np.ones((3,2))
print(ones)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [63]:
arr = [[1,2,3], [4,5,6]]
ones = np.ones_like(arr)
print(ones)
print('Data Type: ' + str(ones.dtype))

[[1 1 1]
 [1 1 1]]
Data Type: int32


# Create an empty array of given shape

- `np.empty()` : create array of empty values in given shape
- `np.empty_like()` : create array of empty values with the same shape and data type as the given input array

### Notice that the initial values are not necessarily set to zeroes.They are just some garbage values in random memory addresses.

In [75]:
empty = np.empty((3,3))
print(empty)

[[2.41907520e-312 1.31932391e-311 2.34480535e-312]
 [2.37663529e-312 2.22809558e-312 2.46151512e-312]
 [2.22523004e-306 2.22522596e-306 5.18768928e-322]]


In [77]:
arr = np.array([[1,2,3], [4,5,6]], dtype=np.int64)
empty = np.empty_like(arr)
print(empty)
print('Data Type: ' + str(empty.dtype))

[[4607182418800017408 4611686018427387904 4613937818241073152]
 [4616189618054758400 4617315517961601024 4618441417868443648]]
Data Type: int64


# Create an array of constant values of given shape

- `np.full()`: create array of constant values in given shape
- `np.full_like()`: create array of constant values with the same shape and data type as the given input array

In [90]:
full = np.full((4,4), 5)
print(full)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [92]:
arr = np.array([[1,2], [3,4]], dtype=np.float64)
full = np.full_like(arr, 5)
print(full)
print('Data Type: ' + str(full.dtype))

[[5. 5.]
 [5. 5.]]
Data Type: float64


# Create an array in a repetitive manneri
1. `np.repeat(iterable, reps, axis=None)` : repeat each element by n times

    - `iterable`: input arr
    - `reps`: no. of repetitions
    - `axis`: which axis to repeat along, default is None which will flatten the input arr and then repeat
  
2. `np.tile()` : repeat the whole arr by n-times

    - iterable: input arr
    - reps: no. of repetitions, it can be tuple to represent repetitions along x and y -axiss
```


In [128]:

# No axis specified, then flatten the input array first and repeat
arr = [[0, 1, 2], [3, 4, 5]]
print(np.repeat(arr, 3)) 

[0 0 0 1 1 1 2 2 2 3 3 3 4 4 4 5 5 5]


In [130]:
# An example of repeating along x-axis
arr = [[0, 1, 2], [3, 4, 5]]
print(np.repeat(arr, 3, axis=0)) 

[[0 1 2]
 [0 1 2]
 [0 1 2]
 [3 4 5]
 [3 4 5]
 [3 4 5]]


In [132]:
# An example of repeating along y-axis
arr = [[0, 1, 2], [3, 4, 5]]
print(np.repeat(arr, 3, axis=1))    

[[0 0 0 1 1 1 2 2 2]
 [3 3 3 4 4 4 5 5 5]]


In [134]:
# Repeat the whole array by a specified number of times
arr = [0, 1, 2]
print(np.tile(arr, 3))

[0 1 2 0 1 2 0 1 2]


In [136]:
# Repeat along specified axes
print(np.tile(arr, (2,2)))


[[0 1 2 0 1 2]
 [0 1 2 0 1 2]]


# Create an identity matrix of given size

- `
np.eye(size, k=0` ): create an identity matrix of given

- `np.identity()` : same as np.eye() but does not carry parametersmeters

In [147]:
identity_matrix = np.eye(5)
print(identity_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [153]:
# An example of diagonal offset
identity_matrix = np.eye(5, k=-1)
print(identity_matrix)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]]


### Create an array with given values on the diagonal


In [158]:
arr = np.random.rand(5,5)
print(arr)

# Extract values on the diagonal\

print('\nValues on the diagonal: ' + str(np.diag(arr)))

[[0.37191957 0.86740782 0.58030333 0.49883383 0.7682499 ]
 [0.99280693 0.65417404 0.42945937 0.79162662 0.81057713]
 [0.59007835 0.17801276 0.13948417 0.14908906 0.80311008]
 [0.53003772 0.40613043 0.80119045 0.27336325 0.78391487]
 [0.07691974 0.12881024 0.39432735 0.52116449 0.53401405]]

Values on the diagonal: [0.37191957 0.65417404 0.13948417 0.27336325 0.53401405]


In [160]:
# Not necessarily to be a square matrix
arr = np.random.rand(10,3)
print(arr)
# Extract values on the diagonal
print('\nValues on the diagonal: ' + str(np.diag(arr)))

[[0.20959344 0.21062153 0.19536044]
 [0.49775723 0.39503128 0.51664851]
 [0.20118385 0.8138266  0.30494008]
 [0.0968381  0.62385591 0.13516302]
 [0.32356686 0.30403633 0.88200168]
 [0.19233079 0.57584259 0.0233268 ]
 [0.67110298 0.91705213 0.08975896]
 [0.20002645 0.88662939 0.15823233]
 [0.44564085 0.49926323 0.43875629]
 [0.96976604 0.33796118 0.53975355]]

Values on the diagonal: [0.20959344 0.39503128 0.30494008]


In [162]:
# Create a matrix given values on the diagonal
# All non-diagonal values set to zeros
arr = np.diag([1,2,3,4,5])
print(arr)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]
