In [1]:
import numpy as np

In [23]:
# set seed
np.random.seed(123)

In [9]:
# set random state which is independent from the global seed
rs = np.random.RandomState(321)
rs.rand(10)

array([0.88594794, 0.07791236, 0.97964616, 0.24767146, 0.75288472,
       0.52667564, 0.90755375, 0.8840703 , 0.08926896, 0.5173446 ])

## generate a random sample from interval [0, 1) in a given shape


In [13]:
# generate a random scalar
print(np.random.rand())    

0.6964691855978616


In [15]:
# generate a 1-D array
print(np.random.rand(3)) 

[0.28613933 0.22685145 0.55131477]


In [27]:
# generate a 2-D array
print(np.random.rand(3,3))    

[[0.39211752 0.34317802 0.72904971]
 [0.43857224 0.0596779  0.39804426]
 [0.73799541 0.18249173 0.17545176]]


## generate a sample from the standard normal distribution (mean = 0, var = 1)

In [33]:
print(np.random.randn(3,3))

[[-0.6377515   0.9071052  -1.4286807 ]
 [-0.14006872 -0.8617549  -0.25561937]
 [-2.79858911 -1.7715331  -0.69987723]]


# generate an array of random integers in a given interval [low, high)

In [43]:
# np.ranodm.randint(low, high, size, dtype)
print(np.random.randint(1, 10, 3, 'i8'))

[1 7 5]


# generate an array of random floating-point numbers in the interval [0.0, 1.0)

In [48]:
# the following methods are the same as np.random.rand()
print(np.random.random_sample(10))
print()
print(np.random.random(10))
print()
print(np.random.ranf(10))
print()
print(np.random.sample(10))

[0.36310407 0.85497282 0.7113918  0.39294441 0.23130148 0.38017471
 0.5491621  0.55671906 0.00413464 0.63802252]

[0.05764801 0.04302691 0.87505113 0.2925876  0.76276766 0.36786526
 0.87350227 0.02942373 0.55204372 0.2402475 ]

[0.88480501 0.46023842 0.19317033 0.2936925  0.81792751 0.55948738
 0.67792545 0.80912668 0.86857215 0.41799246]

[0.05893816 0.478459   0.52115943 0.58063202 0.309199   0.91988263
 0.6553475  0.34924138 0.54109404 0.4490534 ]


# generate a random sample from a given 1-D array


In [60]:
# np.random.choice(iterable_or_int, size, replace=True, p=weights)
np.random.choice(range(3), 8, replace = True,  p=[0.1, 0.8, 0.1])

array([0, 0, 1, 1, 1, 1, 1, 1])

In [62]:
print(np.random.choice(3, 10))


[2 1 1 1 1 1 2 2 1 2]


In [64]:
print(np.random.choice([1,2,3], 10))


[1 2 1 2 2 3 2 3 1 3]


# shuffle an array in place


In [67]:

arr = np.array(range(10))
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [69]:

np.random.shuffle(arr)
print(arr)

[9 6 3 7 0 2 4 1 8 5]


# generate a permutation of an array


In [76]:
# similar to np.random.shuffle(), but it returns a copy rather than making changes in place
arr = np.array(range(3))
print('The initial array: ', arr)
print('A permutation of the array: ', np.random.permutation(arr))

The initial array:  [0 1 2]
A permutation of the array:  [0 2 1]
