# Maths Functions

In [2]:
import numpy as np


In [3]:
arr = np.random.rand(5,5)
arr

array([[0.83633879, 0.04500869, 0.23616948, 0.28729418, 0.14491601],
       [0.61381973, 0.43593393, 0.54050252, 0.06235847, 0.18099269],
       [0.07284436, 0.14761635, 0.55118917, 0.38227185, 0.17071341],
       [0.38334693, 0.01790869, 0.98028072, 0.64908186, 0.31755831],
       [0.99754876, 0.08386622, 0.60045895, 0.10048046, 0.46055075]])

In [4]:
# element-wise addition, subtraction, multiplication and division
print(arr + 10)
print()
print(arr - 10)
print()
print(arr * 10)
print()
print(arr / 10)

[[10.83633879 10.04500869 10.23616948 10.28729418 10.14491601]
 [10.61381973 10.43593393 10.54050252 10.06235847 10.18099269]
 [10.07284436 10.14761635 10.55118917 10.38227185 10.17071341]
 [10.38334693 10.01790869 10.98028072 10.64908186 10.31755831]
 [10.99754876 10.08386622 10.60045895 10.10048046 10.46055075]]

[[-9.16366121 -9.95499131 -9.76383052 -9.71270582 -9.85508399]
 [-9.38618027 -9.56406607 -9.45949748 -9.93764153 -9.81900731]
 [-9.92715564 -9.85238365 -9.44881083 -9.61772815 -9.82928659]
 [-9.61665307 -9.98209131 -9.01971928 -9.35091814 -9.68244169]
 [-9.00245124 -9.91613378 -9.39954105 -9.89951954 -9.53944925]]

[[8.36338793 0.45008695 2.36169477 2.8729418  1.44916011]
 [6.13819733 4.3593393  5.40502517 0.62358471 1.80992694]
 [0.72844362 1.47616353 5.51189166 3.82271847 1.70713413]
 [3.83346928 0.17908687 9.80280717 6.49081865 3.17558307]
 [9.9754876  0.83866224 6.00458948 1.00480459 4.60550752]]

[[0.08363388 0.00450087 0.02361695 0.02872942 0.0144916 ]
 [0.06138197 0.0

In [5]:
# the above operations can be performed using numpy built-in functions
# which can save memory as the output can be stored in the original array rather than assigning new memory
arr1 = np.array([1,2,3])
np.add(arr1, [8,9,10], out=arr1)
print(arr1)

np.subtract(arr1, [8,9,10], out=arr1)
print(arr1)

np.multiply(arr1, [1,2,3], out=arr1)
print(arr1)

[ 9 11 13]
[1 2 3]
[1 4 9]


## element-wise exponentiation


In [7]:
print(np.exp(arr))

[[2.30790178 1.04603695 1.26638892 1.33281624 1.15594248]
 [1.8474748  1.54640662 1.7168694  1.06434381 1.19840642]
 [1.07556312 1.15906814 1.73531537 1.46561045 1.18615077]
 [1.46718695 1.01807001 2.6652043  1.91378291 1.37376934]
 [2.71162683 1.0874834  1.82295525 1.10570203 1.58494666]]


# element-wise logorithm
>

In [9]:
# natural log
print(np.log(arr))  

[[-1.78721493e-01 -3.10089959e+00 -1.44320561e+00 -1.24724857e+00
  -1.93160094e+00]
 [-4.88053988e-01 -8.30264584e-01 -6.15255985e-01 -2.77485575e+00
  -1.70929861e+00]
 [-2.61943015e+00 -1.91313858e+00 -5.95677214e-01 -9.61623283e-01
  -1.76776908e+00]
 [-9.58814884e-01 -4.02246939e+00 -1.99163029e-02 -4.32196430e-01
  -1.14709383e+00]
 [-2.45424937e-03 -2.47853232e+00 -5.10061002e-01 -2.29779201e+00
  -7.75332219e-01]]


In [10]:
# base 2
print(np.log2(arr)) 

[[-2.57840612e-01 -4.47365246e+00 -2.08210558e+00 -1.79939933e+00
  -2.78671110e+00]
 [-7.04113069e-01 -1.19781860e+00 -8.87626758e-01 -4.00327063e+00
  -2.46599663e+00]
 [-3.77903888e+00 -2.76007554e+00 -8.59380562e-01 -1.38732914e+00
  -2.55035168e+00]
 [-1.38327748e+00 -5.80319665e+00 -2.87331514e-02 -6.23527647e-01
  -1.65490658e+00]
 [-3.54073340e-03 -3.57576629e+00 -7.35862479e-01 -3.31501314e+00
  -1.11856795e+00]]


In [11]:
# base 10
print(np.log10(arr)) 

[[-7.76177583e-02 -1.34670358e+00 -6.26776232e-01 -5.41673172e-01
  -8.38883629e-01]
 [-2.11959154e-01 -3.60579327e-01 -2.67202279e-01 -1.20510454e+00
  -7.42338956e-01]
 [-1.13760406e+00 -8.30865528e-01 -2.58699327e-01 -4.17627685e-01
  -7.67732355e-01]
 [-4.16408013e-01 -1.74693626e+00 -8.64954044e-03 -1.87700525e-01
  -4.98176522e-01]
 [-1.06586696e-03 -1.07641291e+00 -2.21516679e-01 -9.97918391e-01
  -3.36722504e-01]]


# element-wise square root


In [13]:
print(np.sqrt(arr))


[[0.91451561 0.21215253 0.48597271 0.5359983  0.38067836]
 [0.78346648 0.66025293 0.73518876 0.24971678 0.42543236]
 [0.26989695 0.38420874 0.74242115 0.61828137 0.4131748 ]
 [0.61915017 0.13382334 0.99009127 0.80565617 0.56352312]
 [0.99877363 0.28959666 0.77489286 0.31698653 0.6786389 ]]


In [14]:
# element-wise sine and cosine
print(np.sin(arr))


[[0.74219442 0.0449935  0.23398016 0.28335835 0.14440932]
 [0.57599411 0.42225717 0.51456694 0.06231806 0.18000614]
 [0.07277996 0.14708083 0.52370065 0.37302929 0.16988544]
 [0.37402656 0.01790773 0.8306537  0.60445524 0.31224788]
 [0.84014405 0.08376795 0.5650212  0.10031146 0.44444154]]


In [15]:
print(np.cos(arr))


[[0.67018464 0.99898728 0.97224137 0.9590141  0.98951804]
 [0.81745384 0.90647608 0.85745021 0.99805634 0.98366549]
 [0.99734802 0.98912448 0.85190236 0.92781957 0.98546382]
 [0.92741799 0.99983964 0.55678939 0.79663911 0.95000066]
 [0.54236333 0.99648529 0.82507639 0.99495608 0.89580786]]


# sum along a specified axis


In [17]:
arr

array([[0.83633879, 0.04500869, 0.23616948, 0.28729418, 0.14491601],
       [0.61381973, 0.43593393, 0.54050252, 0.06235847, 0.18099269],
       [0.07284436, 0.14761635, 0.55118917, 0.38227185, 0.17071341],
       [0.38334693, 0.01790869, 0.98028072, 0.64908186, 0.31755831],
       [0.99754876, 0.08386622, 0.60045895, 0.10048046, 0.46055075]])

In [18]:
# sum along the row
print(np.sum(arr, axis=0))    

[2.90389857 0.73033389 2.90860083 1.48148682 1.27473118]


In [19]:
# sum along the column
print(np.sum(arr, axis=1))  

[1.54972716 1.83360735 1.32463514 2.3481765  2.24290514]


## compute the min and max along a specified axis


In [21]:
# calculate min along the row
print(np.min(arr, axis=0))

[0.07284436 0.01790869 0.23616948 0.06235847 0.14491601]


In [22]:
# calculate max along the column
print(np.max(arr, axis=1)) 

[0.83633879 0.61381973 0.55118917 0.98028072 0.99754876]


In [23]:
# if axis not specified, calculate the max/min value of all elements
print(np.max(arr))
print(np.min(arr))

0.9975487598346944
0.017908686697669873


## compute the indices of the min and max along a specified axis


In [25]:
# along the row
print(np.argmin(arr, axis=0))
print(np.argmax(arr, axis=0))

[2 3 0 1 0]
[4 1 3 3 4]


In [26]:
# along the column
print(np.argmin(arr, axis=1))
print(np.argmax(arr, axis=1))

[1 3 0 1 1]
[0 0 2 2 0]


In [27]:
# if axis not specified, return the index of the flattened array
print(np.argmin(arr))
print(np.argmax(arr))

16
20


# compute element-wise min and max of two arrays


In [29]:
arr1 = np.array([1, 3, 5, 7, 9])
arr2 = np.array([0, 4, 3, 8, 7])
print(np.maximum(arr1, arr2))
print(np.minimum(arr1, arr2))


[1 4 5 8 9]
[0 3 3 7 7]


## split fractional and integral parts of a floating-point array


In [65]:
arr1 = np.random.rand(10) * 10
re, intg = np.modf(arr1)
print(arr1)
print()
print('fractional: ', re)
print()
print('integral: ', intg)

[0.87221193 0.96667951 8.38504904 1.8808737  3.32007997 0.38792521
 5.07120478 2.8817311  1.06981433 0.61739095]

fractional:  [0.87221193 0.96667951 0.38504904 0.8808737  0.32007997 0.38792521
 0.07120478 0.8817311  0.06981433 0.61739095]

integral:  [0. 0. 8. 1. 3. 0. 5. 2. 1. 0.]


# compute the mean


In [68]:
# compute the overall mean
print(np.mean(arr))

0.3719620514945822


In [70]:
# compute the mean along the row
print(arr)
print()
print(np.mean(arr, axis=0))   


[[0.83633879 0.04500869 0.23616948 0.28729418 0.14491601]
 [0.61381973 0.43593393 0.54050252 0.06235847 0.18099269]
 [0.07284436 0.14761635 0.55118917 0.38227185 0.17071341]
 [0.38334693 0.01790869 0.98028072 0.64908186 0.31755831]
 [0.99754876 0.08386622 0.60045895 0.10048046 0.46055075]]

[0.58077971 0.14606678 0.58172017 0.29629736 0.25494624]


In [72]:
# compute the mean along the column
print(np.mean(arr, axis=1)) 

[0.30994543 0.36672147 0.26492703 0.4696353  0.44858103]


# compute the median



In [85]:
# compute the overall median
print(np.median(arr))

0.31755830740018975


In [87]:
# compute the median along the row
print(np.median(arr, axis=0)) 

[0.61381973 0.08386622 0.55118917 0.28729418 0.18099269]


In [89]:
# compute the median along the column
print(np.median(arr, axis=1))

[0.23616948 0.43593393 0.17071341 0.38334693 0.46055075]


# compute the percentile


In [92]:
arr1 = np.random.rand(100)
# compute 5, 65, and 95 percentiles of the array
print(np.percentile(arr1, [5, 65, 95]))

[0.05376085 0.66629636 0.96790671]


# compute the standard deviation & variance


In [95]:
# compute the overall standard deviation
print(np.std(arr))

0.2841802751415273


In [99]:
# compute the standard deviation along the row
print(np.std(arr, axis=0))

# compute the standard deviation along the column
print(np.std(arr, axis=1))

[0.32774275 0.15134828 0.23716575 0.21213262 0.11904993]
[0.27585218 0.21127223 0.17620986 0.32483529 0.34022541]


In [101]:
# compute the overall variance
print(np.var(arr))

0.08075842877951418


In [103]:
# compute the variance along the row
print(np.var(arr, axis=0))

[0.10741531 0.0229063  0.05624759 0.04500025 0.01417289]


In [105]:
# compute the variance along the column
print(np.var(arr, axis=1))

[0.07609443 0.04463596 0.03104991 0.10551797 0.11575333]


# compute the covariance & correlation


In [108]:
arr = np.random.rand(5,8)
print(np.cov(arr))

[[ 0.11397733  0.03860548  0.03469145 -0.05229306 -0.0118081 ]
 [ 0.03860548  0.03446678  0.01490435 -0.00489634  0.00995285]
 [ 0.03469145  0.01490435  0.06582618 -0.00718345 -0.02319293]
 [-0.05229306 -0.00489634 -0.00718345  0.08718274  0.00244981]
 [-0.0118081   0.00995285 -0.02319293  0.00244981  0.02435473]]


In [110]:
print(np.corrcoef(arr[:,0], arr[:,1]))

[[ 1.         -0.71082755]
 [-0.71082755  1.        ]]


# compute cumulative sum & product


In [113]:
# calculate the cumulative sums along the row
print(np.cumsum(arr, axis=0))  

[[0.14835924 0.69572857 0.94208852 0.65276189 0.90511418 0.86359567
  0.16393901 0.9891948 ]
 [0.54479228 1.17025916 1.46724848 1.3190801  1.30751108 1.31181403
  0.1878518  1.50448337]
 [0.86574051 1.56542959 1.91807326 2.16858525 2.20475425 2.18375945
  0.58290616 1.85748883]
 [1.47759398 1.87323034 2.67563897 3.06106101 2.43007692 2.43670504
  1.35822359 1.99927178]
 [2.21331607 2.30503364 3.13646965 3.49201804 2.73496483 2.73478925
  1.63031589 2.56539787]]


In [115]:
# calculate the cumulative sums along the column
print(np.cumsum(arr, axis=1))    

[[0.14835924 0.84408781 1.78617633 2.43893822 3.3440524  4.20764807
  4.37158708 5.36078189]
 [0.39643304 0.87096362 1.39612358 2.0624418  2.4648387  2.91305705
  2.93696984 3.45225841]
 [0.32094823 0.71611867 1.16694344 2.01644859 2.91369176 3.78563718
  4.18069155 4.53369701]
 [0.61185348 0.91965422 1.67721993 2.5696957  2.79501836 3.04796395
  3.82328138 3.96506432]
 [0.73572209 1.16752539 1.62835608 2.05931311 2.36420101 2.66228522
  2.93437752 3.50050362]]


In [117]:
# calculate the cumulative product along the row
print(np.cumprod(arr, axis=0))   

[[1.48359238e-01 6.95728571e-01 9.42088521e-01 6.52761886e-01
  9.05114184e-01 8.63595673e-01 1.63939011e-01 9.89194802e-01]
 [5.88145033e-02 3.30144486e-01 4.94747168e-01 4.34947137e-01
  3.64215140e-01 3.87079433e-01 3.92023883e-03 5.09720774e-01]
 [1.88764108e-02 1.30463340e-01 2.23044282e-01 3.69489830e-01
  3.26789548e-01 3.37512141e-01 1.54870746e-03 1.79934217e-01]
 [1.15495976e-02 4.01567136e-02 1.68970700e-01 3.29760718e-01
  7.36330927e-02 8.53722070e-02 1.20073988e-03 2.55116032e-02]
 [8.49729409e-03 1.73398014e-02 7.78668835e-02 1.42112699e-01
  2.24498395e-02 2.54481065e-02 3.26712081e-04 1.44427842e-02]]


In [119]:
# calculate the cumulative product along the column
print(np.cumprod(arr, axis=1)) 

[[1.48359238e-01 1.03217761e-01 9.72402675e-02 6.34747404e-02
  5.74518879e-02 4.96152018e-02 8.13386711e-03 8.04597906e-03]
 [3.96433037e-01 1.88119601e-01 9.87928818e-02 6.58274970e-02
  2.64887806e-02 1.18727577e-02 2.83910739e-04 1.46295958e-04]
 [3.20948232e-01 1.26829252e-01 5.71777692e-02 4.85728091e-02
  4.35816213e-02 3.80007953e-02 1.50123800e-02 5.29945213e-03]
 [6.11853475e-01 1.88328957e-01 1.42671560e-01 1.27330910e-01
  2.86905402e-02 7.25714558e-03 5.62659143e-03 7.97754702e-04]
 [7.35722092e-01 3.17687226e-01 1.46400022e-01 6.30921188e-02
  1.92360240e-02 5.73395494e-03 1.56016502e-03 8.83250126e-04]]


# element-wise comparison


In [122]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([5,4,3,2,1])


In [124]:
# return an array of bools
print(arr1 == arr2)    
print(arr1 < 3)

[False False  True False False]
[ True  True False False False]
