In [1]:
import numpy as np

In [3]:
arr = np.array(range(100)).reshape((10,10))
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [7]:
# select an element by row and column indices
print(arr[5][5])
# or more concisely
print(arr[5,5])

55
55


# indexing with slicing


In [10]:
print(arr[1:3, 4:6])

[[14 15]
 [24 25]]


In [14]:
# ellipsis slicing: auto-complete the dimensions
arr = np.array(range(16)).reshape(2,2,2,2)
# print(arr)
print()
# equivalent to arr[0,:,:,:]
print(arr[0, ...])  


[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


# assign a scalar to a slice by broadcasting


In [17]:
arr[1:3,:] = 100    # or simply arr[1:3]
arr[:,8:] = 100
print(arr)

[[[[  0   1]
   [  2   3]]

  [[  4   5]
   [  6   7]]]


 [[[100 100]
   [100 100]]

  [[100 100]
   [100 100]]]]


# boolean indexing


In [20]:
arr1 = np.arange(25).reshape((5,5))
bools = np.array([True, True, False, True, False])
print(arr1[bools])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [15 16 17 18 19]]


In [22]:
# negate the condition
print(arr1[~bools])  

[[10 11 12 13 14]
 [20 21 22 23 24]]


In [24]:
arr2 = np.array([1,2,3,4,5])
# multiple conditions
print(arr1[(arr2<2) | (arr2>4)])   

[[ 0  1  2  3  4]
 [20 21 22 23 24]]


# fancy indexing


In [29]:
arr = np.random.rand(10,10)
arr

array([[0.34168944, 0.1225423 , 0.78088726, 0.31722288, 0.61709944,
        0.67207944, 0.86443162, 0.95765668, 0.1942473 , 0.27335124],
       [0.61622672, 0.7204078 , 0.06076616, 0.5296213 , 0.55182115,
        0.62356853, 0.151408  , 0.7367471 , 0.75345906, 0.45571608],
       [0.62123882, 0.51750278, 0.420247  , 0.13859035, 0.57826118,
        0.72195673, 0.75054165, 0.9278075 , 0.71415579, 0.67381174],
       [0.99204168, 0.72096616, 0.71113417, 0.94005757, 0.34538139,
        0.57825276, 0.08038842, 0.3149121 , 0.11430061, 0.46613929],
       [0.15073484, 0.7480605 , 0.4086824 , 0.66667767, 0.53215314,
        0.52432085, 0.37784989, 0.203874  , 0.21489751, 0.89327427],
       [0.31008712, 0.7815384 , 0.2402109 , 0.01873482, 0.17413566,
        0.86377159, 0.60997755, 0.32258825, 0.71483562, 0.05878691],
       [0.41162189, 0.96116056, 0.68510203, 0.40133079, 0.67660067,
        0.87549832, 0.62526822, 0.81704557, 0.34956824, 0.91039761],
       [0.76052673, 0.24226652, 0.0708123

In [31]:
# select arr[3,3], arr[1,2], arr[2,1]
print(arr[[3,1,2], [3,2,1]])    

[0.94005757 0.06076616 0.51750278]


In [33]:
# select rows 3,1,2 and columns 6,4,8 
print(arr[[3,1,2]][:, [6,4,8]])  

[[0.08038842 0.34538139 0.11430061]
 [0.151408   0.55182115 0.75345906]
 [0.75054165 0.57826118 0.71415579]]


# dimension inference


In [36]:
# dimension inference using any negative number (usually -1)
arr = np.array(range(16)).reshape((4,-1))
print(arr.shape)

(4, 4)


# find elements/indices by conditions


In [41]:
arr = np.arange(16).reshape(4,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [43]:
# find the elements greater than 5 and return a flattened array
print(arr[arr>5])    # or arr[np.where(arr>5)]

[ 6  7  8  9 10 11 12 13 14 15]


In [45]:
# return values based on conditions 
# np.where(condition, true_return, false_return)
print(np.where(arr>5, -1, 10))

[[10 10 10 10]
 [10 10 -1 -1]
 [-1 -1 -1 -1]
 [-1 -1 -1 -1]]


In [47]:
# find the indices of the elements on conditions
print(np.argwhere(arr>5))

[[1 2]
 [1 3]
 [2 0]
 [2 1]
 [2 2]
 [2 3]
 [3 0]
 [3 1]
 [3 2]
 [3 3]]
