# Sorting

In [2]:
import numpy as np

In [4]:
arr = np.random.rand(5,5)
arr

array([[0.94799246, 0.68866428, 0.41913207, 0.25703947, 0.4216061 ],
       [0.06645536, 0.23532454, 0.84906966, 0.19713479, 0.2211908 ],
       [0.72772695, 0.07649396, 0.79744011, 0.83841222, 0.21512548],
       [0.22804298, 0.25726296, 0.93818763, 0.35827132, 0.99281668],
       [0.9101987 , 0.53269629, 0.0707089 , 0.15746308, 0.03036832]])

In [6]:
# sort along the row and return a copy
print(np.sort(arr, axis=0))   

[[0.06645536 0.07649396 0.0707089  0.15746308 0.03036832]
 [0.22804298 0.23532454 0.41913207 0.19713479 0.21512548]
 [0.72772695 0.25726296 0.79744011 0.25703947 0.2211908 ]
 [0.9101987  0.53269629 0.84906966 0.35827132 0.4216061 ]
 [0.94799246 0.68866428 0.93818763 0.83841222 0.99281668]]


In [8]:
# sort along the row in place
arr.sort(axis=0)
print(arr)

[[0.06645536 0.07649396 0.0707089  0.15746308 0.03036832]
 [0.22804298 0.23532454 0.41913207 0.19713479 0.21512548]
 [0.72772695 0.25726296 0.79744011 0.25703947 0.2211908 ]
 [0.9101987  0.53269629 0.84906966 0.35827132 0.4216061 ]
 [0.94799246 0.68866428 0.93818763 0.83841222 0.99281668]]


In [10]:

# sort along the column and return a copy
print(np.sort(arr, axis=1))  

[[0.03036832 0.06645536 0.0707089  0.07649396 0.15746308]
 [0.19713479 0.21512548 0.22804298 0.23532454 0.41913207]
 [0.2211908  0.25703947 0.25726296 0.72772695 0.79744011]
 [0.35827132 0.4216061  0.53269629 0.84906966 0.9101987 ]
 [0.68866428 0.83841222 0.93818763 0.94799246 0.99281668]]


In [12]:
# sort along the column in place
arr.sort(axis=1)    
print(arr)

[[0.03036832 0.06645536 0.0707089  0.07649396 0.15746308]
 [0.19713479 0.21512548 0.22804298 0.23532454 0.41913207]
 [0.2211908  0.25703947 0.25726296 0.72772695 0.79744011]
 [0.35827132 0.4216061  0.53269629 0.84906966 0.9101987 ]
 [0.68866428 0.83841222 0.93818763 0.94799246 0.99281668]]


# compute the indices that would sort an array along a specified axis


In [27]:
arr = np.random.rand(5,5)
arr

array([[0.63942423, 0.44476609, 0.69622146, 0.44747812, 0.68720538],
       [0.79383628, 0.92273934, 0.11394592, 0.30988345, 0.42868908],
       [0.9762806 , 0.21324108, 0.86340656, 0.91570637, 0.0865708 ],
       [0.59920196, 0.46867942, 0.36882077, 0.51479836, 0.90479758],
       [0.92264999, 0.61228014, 0.07456081, 0.74493883, 0.45560427]])

In [29]:
# along the row
print(np.argsort(arr, axis=0))

[[3 2 4 1 2]
 [0 0 1 0 1]
 [1 3 3 3 4]
 [4 4 0 4 0]
 [2 1 2 2 3]]


In [31]:
# along the column
print(np.argsort(arr, axis=1))


[[1 3 0 4 2]
 [2 3 4 0 1]
 [4 1 2 3 0]
 [2 1 3 0 4]
 [2 4 1 3 0]]


In [33]:
# if axis=None, return the indices of a flattened array
print(np.argsort(arr, axis=None))

[22 14  7 11  8 17  9  1  3 24 16 18 15 21  0  4  2 23  5 12 19 13 20  6
 10]
