9# Manipulate an array

In [2]:
import numpy as np

In [6]:
arr = np.random.rand(3,4)
arr

array([[0.41135778, 0.83027282, 0.38330158, 0.50277413],
       [0.43279667, 0.14156158, 0.80307928, 0.53416464],
       [0.59302716, 0.6744293 , 0.86738941, 0.22944264]])

 # Transpose an Array

In [9]:
print(arr.T)
# or
print(np.transpose(arr))
# or
print(arr.transpose())

[[0.41135778 0.43279667 0.59302716]
 [0.83027282 0.14156158 0.6744293 ]
 [0.38330158 0.80307928 0.86738941]
 [0.50277413 0.53416464 0.22944264]]
[[0.41135778 0.43279667 0.59302716]
 [0.83027282 0.14156158 0.6744293 ]
 [0.38330158 0.80307928 0.86738941]
 [0.50277413 0.53416464 0.22944264]]
[[0.41135778 0.43279667 0.59302716]
 [0.83027282 0.14156158 0.6744293 ]
 [0.38330158 0.80307928 0.86738941]
 [0.50277413 0.53416464 0.22944264]]


### transpose of a high dimensional array with specified order of axes

In [14]:
arr1 = np.arange(16).reshape((2,2,4))
print(arr1)
print("----------------")
arr1.transpose((1,0,2))
print(arr1)

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]
----------------
[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]


# swap axes

In [17]:
arr1 = np.arange(16).reshape((2,2,4))
print(arr1.swapaxes(1,2))

[[[ 0  4]
  [ 1  5]
  [ 2  6]
  [ 3  7]]

 [[ 8 12]
  [ 9 13]
  [10 14]
  [11 15]]]


# change the shape of an array


In [20]:
# change the shape of an array and return a copy
arr.reshape((2,6))

array([[0.41135778, 0.83027282, 0.38330158, 0.50277413, 0.43279667,
        0.14156158],
       [0.80307928, 0.53416464, 0.59302716, 0.6744293 , 0.86738941,
        0.22944264]])

In [24]:
# change the shape of an array in place
arr.resize((2,6))
arr

array([[0.41135778, 0.83027282, 0.38330158, 0.50277413, 0.43279667,
        0.14156158],
       [0.80307928, 0.53416464, 0.59302716, 0.6744293 , 0.86738941,
        0.22944264]])

## flatten an array


In [32]:
# return a copy
arr.flatten()   

array([0.41135778, 0.83027282, 0.38330158, 0.50277413, 0.43279667,
       0.14156158, 0.80307928, 0.53416464, 0.59302716, 0.6744293 ,
       0.86738941, 0.22944264])

In [34]:
# return a view
# change any element in the view will change the initial array
arr.ravel()      

array([0.41135778, 0.83027282, 0.38330158, 0.50277413, 0.43279667,
       0.14156158, 0.80307928, 0.53416464, 0.59302716, 0.6744293 ,
       0.86738941, 0.22944264])

# append elements to an array

In [41]:
arr = np.array([1,2,3])

In [43]:
# append an array and return a copy
arr2 = np.append(arr, [4,5,6])    
print(arr2)

[1 2 3 4 5 6]


# insert elements into an array

In [46]:
# np.insert(array, position, element)

# insert a scalar at a certain position
arr3 = np.insert(arr, 0, 100)    
print(arr3)

[100   1   2   3]


In [48]:
# insert multiple values at a certain position
arr3 = np.insert(arr, 0, [1,2,3])    
print(arr3)

[1 2 3 1 2 3]


# delete elements from an array


In [51]:
# remove the element at position 0
arr4 = np.delete(arr, 0)    
print(arr4)

[2 3]


In [53]:
# remove the element at multiple positions
arr4 = np.delete(arr, [0,2])    
print(arr4)

[2]


# copy an array


In [56]:
arr = np.array([1,2,3])


In [58]:
# the following methods are all deep copy
arr1 = np.copy(arr)
# or 
arr1 = arr.copy()
# or 
arr1 = np.array(arr, copy=True)