# Combine & Split an Array

In [3]:
import numpy as np

In [5]:
arr1 = np.array([[1,2,3,4], [1,2,3,4]])
arr2 = np.array([[5,6,7,8], [5,6,7,8]])


In [7]:
# concat along the row
cat = np.concatenate((arr1, arr2), axis=0)        
print(cat)

[[1 2 3 4]
 [1 2 3 4]
 [5 6 7 8]
 [5 6 7 8]]


In [9]:

# concat along the column
cat = np.concatenate((arr1, arr2), axis=1)    
print(cat)

[[1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]]


In [11]:
# stack arrays vertically
cat = np.vstack((arr1, arr2))
print(cat)

[[1 2 3 4]
 [1 2 3 4]
 [5 6 7 8]
 [5 6 7 8]]


In [13]:
# stack arrays vertically
cat = np.r_[arr1, arr2]
print(cat)

[[1 2 3 4]
 [1 2 3 4]
 [5 6 7 8]
 [5 6 7 8]]


In [15]:
# stack arrays horizontally
cat = np.hstack((arr1, arr2))
print(cat)

[[1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]]


In [17]:
# stack arrays horizontally
cat = np.c_[arr1, arr2]
print(cat)


[[1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]]


# split an array


In [26]:
arr = np.random.rand(6,6)
arr

array([[0.75734353, 0.83771568, 0.20764225, 0.97267024, 0.23185548,
        0.7793301 ],
       [0.51635189, 0.42827835, 0.30186707, 0.61228284, 0.60797517,
        0.53542808],
       [0.1716749 , 0.72959139, 0.533266  , 0.51630052, 0.0083643 ,
        0.99541762],
       [0.16756348, 0.54114796, 0.2619081 , 0.11981685, 0.13009422,
        0.96066202],
       [0.47265483, 0.36797917, 0.23040023, 0.64374005, 0.69305494,
        0.35097805],
       [0.66204705, 0.99258924, 0.80906959, 0.66596374, 0.84780017,
        0.36800015]])

In [32]:
# split the array vertically into n evenly spaced chunks
arr1 = np.vsplit(arr, 2)
print(arr1)

[array([[0.75734353, 0.83771568, 0.20764225, 0.97267024, 0.23185548,
        0.7793301 ],
       [0.51635189, 0.42827835, 0.30186707, 0.61228284, 0.60797517,
        0.53542808],
       [0.1716749 , 0.72959139, 0.533266  , 0.51630052, 0.0083643 ,
        0.99541762]]), array([[0.16756348, 0.54114796, 0.2619081 , 0.11981685, 0.13009422,
        0.96066202],
       [0.47265483, 0.36797917, 0.23040023, 0.64374005, 0.69305494,
        0.35097805],
       [0.66204705, 0.99258924, 0.80906959, 0.66596374, 0.84780017,
        0.36800015]])]


In [34]:
# split the array horizontally into n evenly spaced chunks
arr2 = np.hsplit(arr, 2)
print(arr2)

[array([[0.75734353, 0.83771568, 0.20764225],
       [0.51635189, 0.42827835, 0.30186707],
       [0.1716749 , 0.72959139, 0.533266  ],
       [0.16756348, 0.54114796, 0.2619081 ],
       [0.47265483, 0.36797917, 0.23040023],
       [0.66204705, 0.99258924, 0.80906959]]), array([[0.97267024, 0.23185548, 0.7793301 ],
       [0.61228284, 0.60797517, 0.53542808],
       [0.51630052, 0.0083643 , 0.99541762],
       [0.11981685, 0.13009422, 0.96066202],
       [0.64374005, 0.69305494, 0.35097805],
       [0.66596374, 0.84780017, 0.36800015]])]
